/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AdvancedTransit {
  export type TicketStruct = {
    ticketId: BigNumberish;
    owner: AddressLike;
    activationTime: BigNumberish;
    isActive: boolean;
    allowedPath: string[];
    scannedStops: string[];
  };

  export type TicketStructOutput = [
    ticketId: bigint,
    owner: string,
    activationTime: bigint,
    isActive: boolean,
    allowedPath: string[],
    scannedStops: string[]
  ] & {
    ticketId: bigint;
    owner: string;
    activationTime: bigint;
    isActive: boolean;
    allowedPath: string[];
    scannedStops: string[];
  };
}

export interface AdvancedTransitInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyTicket"
      | "getMyValidTickets"
      | "nextTicketId"
      | "scanTicket"
      | "tickets"
      | "userTickets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TicketScanned" | "TicketTransfer"
  ): EventFragment;

  encodeFunctionData(functionFragment: "buyTicket", values: [string[]]): string;
  encodeFunctionData(
    functionFragment: "getMyValidTickets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTicketId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scanTicket",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "tickets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userTickets",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buyTicket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMyValidTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTicketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scanTicket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tickets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userTickets",
    data: BytesLike
  ): Result;
}

export namespace TicketScannedEvent {
  export type InputTuple = [
    ticketId: BigNumberish,
    stopName: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    ticketId: bigint,
    stopName: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    ticketId: bigint;
    stopName: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketTransferEvent {
  export type InputTuple = [
    ticketId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [ticketId: bigint, from: string, to: string];
  export interface OutputObject {
    ticketId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AdvancedTransit extends BaseContract {
  connect(runner?: ContractRunner | null): AdvancedTransit;
  waitForDeployment(): Promise<this>;

  interface: AdvancedTransitInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyTicket: TypedContractMethod<[_path: string[]], [void], "payable">;

  getMyValidTickets: TypedContractMethod<
    [_user: AddressLike],
    [AdvancedTransit.TicketStructOutput[]],
    "view"
  >;

  nextTicketId: TypedContractMethod<[], [bigint], "view">;

  scanTicket: TypedContractMethod<
    [_ticketId: BigNumberish, _currentStop: string],
    [void],
    "nonpayable"
  >;

  tickets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean] & {
        ticketId: bigint;
        owner: string;
        activationTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  userTickets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyTicket"
  ): TypedContractMethod<[_path: string[]], [void], "payable">;
  getFunction(
    nameOrSignature: "getMyValidTickets"
  ): TypedContractMethod<
    [_user: AddressLike],
    [AdvancedTransit.TicketStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextTicketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "scanTicket"
  ): TypedContractMethod<
    [_ticketId: BigNumberish, _currentStop: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tickets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean] & {
        ticketId: bigint;
        owner: string;
        activationTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userTickets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "TicketScanned"
  ): TypedContractEvent<
    TicketScannedEvent.InputTuple,
    TicketScannedEvent.OutputTuple,
    TicketScannedEvent.OutputObject
  >;
  getEvent(
    key: "TicketTransfer"
  ): TypedContractEvent<
    TicketTransferEvent.InputTuple,
    TicketTransferEvent.OutputTuple,
    TicketTransferEvent.OutputObject
  >;

  filters: {
    "TicketScanned(uint256,string,uint256)": TypedContractEvent<
      TicketScannedEvent.InputTuple,
      TicketScannedEvent.OutputTuple,
      TicketScannedEvent.OutputObject
    >;
    TicketScanned: TypedContractEvent<
      TicketScannedEvent.InputTuple,
      TicketScannedEvent.OutputTuple,
      TicketScannedEvent.OutputObject
    >;

    "TicketTransfer(uint256,address,address)": TypedContractEvent<
      TicketTransferEvent.InputTuple,
      TicketTransferEvent.OutputTuple,
      TicketTransferEvent.OutputObject
    >;
    TicketTransfer: TypedContractEvent<
      TicketTransferEvent.InputTuple,
      TicketTransferEvent.OutputTuple,
      TicketTransferEvent.OutputObject
    >;
  };
}
