/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AdvancedTransit {
  export type TicketStruct = {
    ticketId: BigNumberish;
    userId: string;
    activationTime: BigNumberish;
    isActive: boolean;
    allowedPath: string[];
    scannedStops: string[];
  };

  export type TicketStructOutput = [
    ticketId: bigint,
    userId: string,
    activationTime: bigint,
    isActive: boolean,
    allowedPath: string[],
    scannedStops: string[]
  ] & {
    ticketId: bigint;
    userId: string;
    activationTime: bigint;
    isActive: boolean;
    allowedPath: string[];
    scannedStops: string[];
  };
}

export interface AdvancedTransitInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "getTicketDetails"
      | "issueTicket"
      | "nextTicketId"
      | "scanTicket"
      | "tickets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TicketIssued" | "TicketScanned"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTicketDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "issueTicket",
    values: [string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTicketId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scanTicket",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "tickets",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTicketDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTicketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scanTicket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tickets", data: BytesLike): Result;
}

export namespace TicketIssuedEvent {
  export type InputTuple = [ticketId: BigNumberish, userId: string];
  export type OutputTuple = [ticketId: bigint, userId: string];
  export interface OutputObject {
    ticketId: bigint;
    userId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketScannedEvent {
  export type InputTuple = [
    ticketId: BigNumberish,
    stopName: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    ticketId: bigint,
    stopName: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    ticketId: bigint;
    stopName: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AdvancedTransit extends BaseContract {
  connect(runner?: ContractRunner | null): AdvancedTransit;
  waitForDeployment(): Promise<this>;

  interface: AdvancedTransitInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  getTicketDetails: TypedContractMethod<
    [_ticketId: BigNumberish],
    [AdvancedTransit.TicketStructOutput],
    "view"
  >;

  issueTicket: TypedContractMethod<
    [_userId: string, _path: string[]],
    [void],
    "nonpayable"
  >;

  nextTicketId: TypedContractMethod<[], [bigint], "view">;

  scanTicket: TypedContractMethod<
    [_ticketId: BigNumberish, _currentStop: string],
    [void],
    "nonpayable"
  >;

  tickets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean] & {
        ticketId: bigint;
        userId: string;
        activationTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTicketDetails"
  ): TypedContractMethod<
    [_ticketId: BigNumberish],
    [AdvancedTransit.TicketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueTicket"
  ): TypedContractMethod<
    [_userId: string, _path: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextTicketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "scanTicket"
  ): TypedContractMethod<
    [_ticketId: BigNumberish, _currentStop: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tickets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean] & {
        ticketId: bigint;
        userId: string;
        activationTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TicketIssued"
  ): TypedContractEvent<
    TicketIssuedEvent.InputTuple,
    TicketIssuedEvent.OutputTuple,
    TicketIssuedEvent.OutputObject
  >;
  getEvent(
    key: "TicketScanned"
  ): TypedContractEvent<
    TicketScannedEvent.InputTuple,
    TicketScannedEvent.OutputTuple,
    TicketScannedEvent.OutputObject
  >;

  filters: {
    "TicketIssued(uint256,string)": TypedContractEvent<
      TicketIssuedEvent.InputTuple,
      TicketIssuedEvent.OutputTuple,
      TicketIssuedEvent.OutputObject
    >;
    TicketIssued: TypedContractEvent<
      TicketIssuedEvent.InputTuple,
      TicketIssuedEvent.OutputTuple,
      TicketIssuedEvent.OutputObject
    >;

    "TicketScanned(uint256,string,uint256)": TypedContractEvent<
      TicketScannedEvent.InputTuple,
      TicketScannedEvent.OutputTuple,
      TicketScannedEvent.OutputObject
    >;
    TicketScanned: TypedContractEvent<
      TicketScannedEvent.InputTuple,
      TicketScannedEvent.OutputTuple,
      TicketScannedEvent.OutputObject
    >;
  };
}
